# NumPy Arrays

In [22]:
my_list=[1,2,3,4]

In [2]:
my_list

[1, 2, 3, 4]

In [5]:
import numpy as np

In [23]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
my_mat=[[1,2,3],[4,5,6]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [35]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [6]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Unifrom distribution

In [15]:
np.random.rand(5)

array([0.97091185, 0.62059127, 0.49828219, 0.02355473, 0.86872377])

# Standard distribution

In [19]:
np.random.randn(5,5)

array([[ 0.36344945,  0.94714221,  1.2602952 ,  0.2469608 , -0.30678508],
       [ 0.29685305, -0.17365017,  0.10949084, -1.81795358, -1.41778942],
       [-0.15993458,  2.42693012,  0.59317197, -0.12483867, -0.33651644],
       [-0.70146809, -0.12844161, -0.77508575, -1.09577933, -0.66478603],
       [ 0.01662556,  0.44104768, -1.89942184,  0.09791999,  0.96195196]])

In [20]:
np.random.randint(1,100,15)

array([61, 43, 84, 89, 11, 72, 11, 84, 32, 64, 40, 80, 29, 24, 54])

In [30]:
arr=arr.reshape(2,2)

In [31]:
arr

array([[1, 2],
       [3, 4]])

In [25]:
ranarr=np.random.randint(0,50,10)

In [26]:
ranarr

array([32, 14, 30, 22, 24,  1, 20, 48, 33,  1])

In [27]:
ranarr.max()

48

In [32]:
arr.shape

(2, 2)

In [34]:
arr.dtype

dtype('int32')

In [35]:
from numpy.random import rand

In [37]:
rand(10)

array([0.07342564, 0.56368517, 0.50056853, 0.77871325, 0.13581968,
       0.59624912, 0.86829106, 0.7442009 , 0.65769055, 0.0642565 ])

In [45]:
arr=np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[5:] #Everything beyond index 5 not from index 5

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[:5]#It will take the number of elements as mentioned after slice operator

array([0, 1, 2, 3, 4])

In [8]:
from numpy.random import randint

In [14]:
arr=randint(1,60,6)

In [15]:
arr

array([33, 39, 21, 54, 12, 28])

In [16]:
arr[0:4]=20

In [17]:
arr

array([20, 20, 20, 20, 12, 28])

In [18]:
arr=np.arange(15)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
slice_arr=arr[0:6]

In [21]:
print(slice_arr)

[0 1 2 3 4 5]


In [23]:
slice_arr[:]=55

In [28]:
slice_arr[7:8]=66

In [25]:
arr

array([55, 55, 55, 55, 55, 55,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr_copy=arr.copy()

In [27]:
arr_copy

array([55, 55, 55, 55, 55, 55,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
arr[6:8]=66

In [32]:
arr

array([55, 55, 55, 55, 55, 55, 66, 66,  8,  9, 10, 11, 12, 13, 14])

In [33]:
arr_copy

array([55, 55, 55, 55, 55, 55,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
A[1][1]

5

In [40]:
A[1,1]

5

In [50]:
A[1:,:2]#Remeber in anything list, array for value before : include and for value after : excludes 

array([[4, 5],
       [7, 8]])

In [51]:
A[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [53]:
A[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [57]:
arr_2d=np.arange(40).reshape(8,5)

In [58]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [66]:
arr_2d[3:6,1:4]

array([[16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
arr/arr

c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
arr**(1/2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [77]:
np.max(arr)

10

In [78]:
arr.max()

10

In [79]:
1/arr

c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])